### ISSUE TITLE
Wrapper scripts for creating new bash scripts

### ISSUE THREAD

**Issue by fbzwsqualitasag** [fbzwsqualitasag/qbashtools#2]
Different types of new bash scripts can be created using different templates. The most often used scripts can be encapsulated in a wrapper

**Comment by pvrqualitasag** [comment]
The wrapper scripts 'nbsaro.sh', 'nbsasc.sh', and 'nbutsc.sh' are generated and installed under /qualstorzws01/data_projekte/linuxBin
